## Objective
Parses a text file table that has reinsurance and risk adjustment data for a benefit year into a CSV.

### Preprocessing
step 1: copy into raw text file

step 2: delete header 

HIOS ID
HIOS INPUTTED
INSURANCE COMPANY
NAME STATE
REINSURANCE
PAYMENT
AMOUNT (OR
NOT ELIGIBLE)
HHS RISK
ADJUSTMENT
TRANSFER
AMOUNT
(INDIVIDUAL
MARKET,
INCLUDING
CATASTROPHIC)
HHS RISK
ADJUSTMENT
TRANSFERS
AMOUNT (SMALL
GROUP MARKET)

step 3: delete page numbers through the regexp ^RI RA.\*

step 4: remove blank lines through the regexp ^\n\n

step 5: find and replace "not eligible" with "N/E"

step 6: find and replace "\$ -" with "\$-"

step 7: find and replace "\$ " with "\$" (also works for step 6)

step 8: find and replace "N/A - MA Issuer" with "N/A_MA_Issuer" (dataframe has trouble parsing "-")

step 9: find and replace "N/A - Default Charge" with "N/A_DefaultCharge"

step 10: delete footnotes on the first page

In [6]:
import pandas as pd
# import re

In [7]:
#with open('2014-Benefit-Year-Edit.txt', 'r') as myfile:
with open('input/2015-Benefit-Year-Edit-Not-Updated.txt', 'r') as myfile:
    s = myfile.read()

In [8]:
split = str.split(s)
length = len(split)

In [9]:
storage = pd.DataFrame(columns=["HIOS ID", "HIOS INPUTTED INSURANCE COMPANY NAME", "STATE", "REINSURANCE PAYMENT AMOUNT (OR NOT ELIGIBLE)",
               "HHS RISK ADJUSTMENT TRANSFER AMOUNT (INDIVIDUAL MARKET, INCLUDING CATASTROPHIC)",
               "HHS RISK ADJUSTMENT TRANSFERS AMOUNT (SMALL GROUP MARKET)"])

# prog = re.compile('^[A-Z]{2}$')

i = 0
index = 0
while i < length - 1:
    hios_id = split[i]
    i = i + 1
    temp = i
    # while (prog.match(split[i]) == None or split[i] in ['US', 'BC', 'OF']): # look for state in quotes
    while (split[i] != 'N/E' and split[i][:1] != '$'):
        i = i + 1
    company_name = str(' '.join(split[temp:i - 1]))
    state = split[i - 1]
    reinsurance = split[i]
    i = i + 1
    individual = split[i]
    i = i + 1
    small_group = split[i] 
    i = i + 1
    storage.loc[index] = [hios_id, company_name, state, reinsurance, individual, small_group]
    index = index + 1
    
print(storage)

    HIOS ID              HIOS INPUTTED INSURANCE COMPANY NAME STATE  \
0     11082                      Aetna Life Insurance Company    AK
1     38344          Premera Blue Cross Blue Shield of Alaska    AK
2     38596                            Time Insurance Company    AK
3     62637                 John Alden Life Insurance Company    AK
4     73836                            Moda Health Plan, Inc.    AK
5     80049               United Healthcare Insurance Company    AK
6     13939                            Time Insurance Company    AL
7     44580                          Humana Insurance Company    AL
8     44902                Federated Mutual Insurance Company    AL
9     46944             Blue Cross and Blue Shield of Alabama    AL
10    49771                 John Alden Life Insurance Company    AL
11    59809          United Healthcare Life Insurance Company    AL
12    68259                United Healthcare of Alabama, Inc.    AL
13    69461               United Healthcare Insurance Company    AL
14    93018                                       VIVA Health    AL
15    93122                            Freedom Life Insurance    AL
16    13262                                HMO Partners, Inc.    AR
17    22732          United Healthcare Ins Co of River Valley    AR
18     Time                                 Insurance Company    AR
19    37903  QualChoice Life & Health Insurance Company, Inc.    AR
20    51826                 John Alden Life Insurance Company    AR
21    53135          United Healthcare Life Insurance Company    AR
22    60079                          Coventry Health and Life    AR
23    61273                            Freedom Life Insurance    AR
24    62141                          Celtic Insurance Company    AR
25    65817               United Healthcare of Arkansas, Inc.    AR
26    70525                             QCA Health Plan, Inc.    AR
27    75293               Arkansas Blue Cross and Blue Shield    AR
28    81392               United Healthcare Insurance Company    AR
29    89365                Federated Mutual Insurance Company    AR
..      ...                                               ...   ...
802   84670                             WPS Health Plan, Inc.    WI
803   87416              Common Ground Healthcare Cooperative    WI
804   89106          United Healthcare Life Insurance Company    WI
805   90028                    BCBS of Wisconsin(Anthem BCBS)    WI
806   91058                       Gundersen Health Plan, Inc.    WI
807   91604                          Humana Insurance Company    WI
808   92708                Federated Mutual Insurance Company    WI
809   94073                            Time Insurance Company    WI
810   94529                     Group Health Cooperative- SCW    WI
811   94720                 John Alden Life Insurance Company    WI
812   14414                Federated Mutual Insurance Company    WV
813   26661              Coventry Health & Life Insurance Co.    WV
814   31274     Highmark Blue Cross Blue Shield West Virginia    WV
815   33577       Coventry Health Care of West Virginia, Inc.    WV
816   35992                            Time Insurance Company    WV
817   44434                    Aetna Health Inc. (a PA corp.)    WV
818   48421                 John Alden Life Insurance Company    WV
819   50318                      Aetna Life Insurance Company    WV
820   59772                             THP Insurance Company    WV
821   72982          The Health Plan of the Upper Ohio Valley    WV
822   77060               United Healthcare Insurance Company    WV
823   95628                              Optimum Choice, Inc.    WV
824   11269                 Blue Cross Blue Shield of Wyoming    WY
825   29941                            Time Insurance Company    WY
826   47823                            Freedom Life Insurance    WY
827   49290                          Celtic Insurance Company    WY
828   49714               United Healthcare Insurance Company    WY
829   53189                                WINhealth Partners    WY
830   72208                 John Alden Life Insurance Company    WY
831   79022                          Altius Health Plans Inc.    WY

    REINSURANCE PAYMENT AMOUNT (OR NOT ELIGIBLE)  \
0                                          $0.00
1                                 $14,647,542.06
2                                  $1,166,760.16
3                                            N/E
4                                 $26,291,860.29
5                                            N/E
6                                    $451,875.61
7                                  $4,106,399.00
8                                            N/E
9                                 $96,795,298.27
10                                           N/E
11                                   $147,985.51
12                                 $7,830,979.30
13                                           N/E
14                                           N/E
15                                         $0.00
16                                           N/E
17                                           N/E
18                                   $852,994.87
19                                 $4,993,056.46
20                                           N/E
21                                   $506,400.88
22                                         $0.00
23                                         $0.00
24                                 $8,194,603.78
25                                           N/E
26                                $10,575,851.65
27                                $64,786,425.56
28                                           N/E
29                                           N/E
..                                           ...
802                               $12,623,708.65
803                               $32,233,096.93
804                                $2,292,719.96
805                                          N/E
806                                $5,244,496.83
807                                $1,894,133.60
808                                          N/E
809                                $3,358,780.94
810                                  $486,164.46
811                                          N/E
812                                          N/E
813                                          N/E
814                               $33,439,790.26
815                                        $0.00
816                                  $431,267.52
817                                        $0.00
818                                          N/E
819                                          N/E
820                                          N/E
821                                   $11,643.23
822                                          N/E
823                                          N/E
824                               $12,710,341.88
825                                $1,887,433.38
826                                   $89,760.56
827                                        $0.00
828                                          N/E
829                                $8,897,182.72
830                                          N/E
831                                        $0.00

    HHS RISK ADJUSTMENT TRANSFER AMOUNT (INDIVIDUAL MARKET, INCLUDING CATASTROPHIC)  \
0                                         $(34,550.55)
1                                       $12,358,455.76
2                                      $(2,908,793.99)
3                                                   $-
4                                      $(9,415,111.19)
5                                                   $-
6                                        $(223,260.20)
7                                      $(3,473,430.83)
8                                                   $-
9                                       $13,434,646.95
10                                                  $-
11                                       $(805,865.40)
12                                     $(8,989,541.02)
13                                                  $-
14                                                  $-
15                                          $57,450.42
16                                                  $-
17                                                  $-
18                                       $(668,914.23)
19                                     $(2,751,129.36)
20                                                  $-
21                                       $(280,355.58)
22                                        $(15,072.70)
23                                         $(5,029.01)
24                                    $(10,893,205.76)
25                                                  $-
26                                       $6,656,762.38
27                                       $8,441,174.73
28                                                  $-
29                                                  $-
..                                                 ...
802                                      $1,825,501.39
803                                        $194,955.10
804                                    $(1,371,221.77)
805                                                 $-
806                                      $(855,334.89)
807                                        $596,881.13
808                                                 $-
809                                      $2,979,855.24
810                                      $1,059,019.73
811                                                 $-
812                                                 $-
813                                                 $-
814                                       $(71,601.45)
815                                          $(435.24)
816                                        $382,756.67
817                                      $(295,477.04)
818                                                 $-
819                                                 $-
820                                                 $-
821                                       $(15,242.90)
822                                                 $-
823                                                 $-
824                                      $1,438,732.96
825                                      $1,254,913.51
826                                         $18,632.31
827                                        $(7,210.87)
828                                                 $-
829                                    $(2,626,798.16)
830                                                 $-
831                                       $(78,269.70)

    HHS RISK ADJUSTMENT TRANSFERS AMOUNT (SMALL GROUP MARKET)
0                                          $557,129.08
1                                        $1,742,413.11
2                                      $(1,465,993.25)
3                                          $607,207.25
4                                        $(683,234.43)
5                                        $(757,521.80)
6                                         $(18,832.66)
7                                                   $-
8                                         $(18,268.78)
9                                        $1,891,994.10
10                                          $47,439.27
11                                           $2,012.29
12                                       $(397,175.98)
13                                       $(724,205.96)
14                                       $(782,962.27)
15                                                  $-
16                                         $681,450.22
17                                  $(737,381.21)30991
18                                       $(271,493.27)
19                                        $(17,495.48)
20                                         $(7,856.65)
21                                                  $-
22                                        $(41,289.01)
23                                                  $-
24                                                  $-
25                                       $(578,563.20)
26                                       $(272,007.50)
27                                       $1,078,908.44
28                                           $9,059.95
29                                          $65,077.18
..                                                 ...
802                                    $(1,158,565.40)
803                                    $(2,056,055.51)
804                                                 $-
805                                      $(163,325.20)
806                                    $(6,517,699.11)
807                                      $1,292,326.01
808                                        $678,006.47
809                                        $405,231.13
810                                      $1,443,408.15
811                                         $44,877.57
812                                        $109,960.53
813                                      $(516,628.21)
814                                      $1,261,985.57
815                                       $(69,535.77)
816                                       $(39,194.65)
817                                      $(562,420.22)
818                                        $224,713.34
819                                        $154,836.76
820                                       $(62,874.74)
821                                      $(553,884.06)
822                                      $(100,035.49)
823                                        $153,076.85
824                                      $(735,310.56)
825                                        $646,260.58
826                                                 $-
827                                                 $-
828                                      $(325,977.41)
829                                       $(31,069.24)
830                                        $599,763.48
831                                      $(153,666.93)

[832 rows x 6 columns]

In [10]:
# save it
storage.to_csv("output/2015-Benefit-Year-RI-RA-Not-Updated.csv")